/// <reference types="node" />
/**
 * Build-time codegen for `.help.md` glob discovery.
 *
 * Scans a directory for `*.help.md` files and writes a TypeScript module
 * that imports each one and re-exports them as a `Record<string, string>`
 * suitable for passing to `helpPlugin({files, ...})`.
 *
 * Used by the `sanity-plugin-help codegen` CLI but also exposed
 * programmatically for users who want to wire it into their own build
 * pipeline (Vite plugin, Next.js plugin, etc):
 *
 *     import {generateHelpFiles} from 'sanity-plugin-help/codegen'
 *
 *     generateHelpFiles({
 *       inputDir: 'sanity/schemas',
 *       outputFile: 'sanity/help-files.ts',
 *     })
 */
import {existsSync, mkdirSync, readdirSync, writeFileSync} from 'node:fs'
import {dirname, join, relative, resolve} from 'node:path'

export interface GenerateHelpFilesOptions {
  /**
   * Directory to scan recursively for `*.help.md` files. Resolved against
   * `process.cwd()`. Defaults to `./sanity/schemas`.
   */
  inputDir?: string

  /**
   * Path to the generated TypeScript module. Resolved against
   * `process.cwd()`. The parent directory is created if missing.
   * Defaults to `./sanity/help-files.ts`.
   */
  outputFile?: string
}

export interface GenerateHelpFilesResult {
  /** Number of `.help.md` files discovered and imported. */
  filesWritten: number

  /** Absolute paths of the discovered `.help.md` files. */
  helpFiles: string[]

  /** Absolute path of the generated TypeScript file. */
  outputFileAbs: string
}

/**
 * Walks `inputDir` and writes an aggregated import file at `outputFile`.
 * Returns a small report you can log from the calling code.
 */
export function generateHelpFiles(options: GenerateHelpFilesOptions = {}): GenerateHelpFilesResult {
  const inputDir = options.inputDir ?? './sanity/schemas'
  const outputFile = options.outputFile ?? './sanity/help-files.ts'
  const inputDirAbs = resolve(process.cwd(), inputDir)
  const outputFileAbs = resolve(process.cwd(), outputFile)
  const outputDir = dirname(outputFileAbs)

  if (!existsSync(inputDirAbs)) {
    throw new Error(
      `[sanity-plugin-help] inputDir not found: ${inputDirAbs}\n` +
        `Pass --in <path> to point at the directory that contains your *.help.md files.`,
    )
  }

  const helpFiles: string[] = []
  collectHelpFiles(inputDirAbs, helpFiles)
  helpFiles.sort()

  const importLines: string[] = []
  const entryLines: string[] = []
  helpFiles.forEach((file, index) => {
    const relPath = relative(outputDir, file).replace(/\\/g, '/')
    const importPath = relPath.startsWith('.') ? relPath : `./${relPath}`
    const varName = `help${index}`
    const basename = file.split(/[\\/]/).pop() ?? ''
    importLines.push(`import ${varName} from '${importPath}'`)
    entryLines.push(`  '${basename}': ${varName},`)
  })

  const content = `${[
    `// This file is auto-generated by \`sanity-plugin-help codegen\`. Do not edit.`,
    `// Re-run \`sanity-plugin-help codegen\` after adding, removing, or renaming a *.help.md file,`,
    `// or run with \`--watch\` to keep it in sync during development.`,
    ``,
    ...importLines,
    ``,
    `export const helpFiles: Record<string, string> = {`,
    ...entryLines,
    `}`,
  ].join('\n')}\n`

  mkdirSync(outputDir, {recursive: true})
  writeFileSync(outputFileAbs, content, 'utf8')

  return {filesWritten: helpFiles.length, helpFiles, outputFileAbs}
}

function collectHelpFiles(dir: string, results: string[]): void {
  for (const entry of readdirSync(dir, {withFileTypes: true})) {
    if (entry.name === 'node_modules' || entry.name.startsWith('.')) continue
    const full = join(dir, entry.name)
    if (entry.isDirectory()) collectHelpFiles(full, results)
    else if (entry.isFile() && /\.help\.md$/.test(entry.name)) results.push(full)
  }
}
